/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package libsiah;

import org.junit.Test;
import static org.junit.Assert.*;

public class LinkedListTest {
    @Test 
    public void constructor_withInteger_successful() {
        LinkedList<Integer> list = new LinkedList<>(1);

        assertEquals(Integer.valueOf(1), list.getVal());
    }

    @Test 
    public void constructor_withString_successful() {
        LinkedList<String> list = new LinkedList<>("1");

        assertEquals(list.getVal(), "1");
    }

    @Test
    public void getNext_withNullConstructor_returnsNull() {
        LinkedList<Integer> list = new LinkedList<>(1);

        assertNull(list.getNext());
    }

    @Test
    public void getVal_withNullConstructor_returnsNull() {
        LinkedList<Integer> list = new LinkedList<>();

        assertNull(list.getVal());
    }

    @Test
    public void getNext_withMultipleNodes_returnsCorrectNode() {
        LinkedList<Integer> node2 = new LinkedList<>(2);
        LinkedList<Integer> node1 = new LinkedList<>(1, node2);

        assertEquals(Integer.valueOf(2), node1.getNext().getVal());
    }
}
